
DAY_PNGS := $(wildcard icons/day/*.png)
NIGHT_PNGS := $(wildcard icons/night/*.png)

define XXD_file
xxd -i $(1) >> include/icons/icons.h;
endef

all:  
	rm -f include/icons/icons.h
	$(foreach png, $(DAY_PNGS), $(call XXD_file,$(png)))
	$(foreach png, $(NIGHT_PNGS), $(call XXD_file,$(png)))

.PHONY:  all
